### ISSUE TITLE
Use Cases descriptions (M1)

### ISSUE THREAD

**Issue by junweilam** [junweilam/ICT2101-Team-Project-P4-5#14]

**Comment by mrdylanchew** [comment]
![Image](https://user-images.githubusercontent.com/94624889/197090813-fc9d68c3-5901-46a0-9df8-36c36f19a4b7.PNG)



![Image](https://user-images.githubusercontent.com/94624889/197090885-e17f7f32-3cdd-4f9d-a0de-e446aa44032d.PNG)



![Image](https://user-images.githubusercontent.com/94624889/197090952-b46ebb61-9748-490f-9533-4af8f9d16748.PNG)



![Image](https://user-images.githubusercontent.com/94624889/197090994-72fea107-4583-443b-a924-3834e17c8938.PNG)



![Image](https://user-images.githubusercontent.com/94624889/197091035-2ea9a863-5590-47fc-8d59-545357b9784f.PNG)



![Image](https://user-images.githubusercontent.com/94624889/197091151-36de8731-1cdc-4c9d-8cc9-3ac153b43934.PNG)



![Image](https://user-images.githubusercontent.com/94624889/197091202-a56d05e5-3652-4e22-94f9-d121bde1fc6e.PNG)


![Image](https://user-images.githubusercontent.com/94624889/197091338-2f646ca3-6876-44c1-b25b-5e5482ba9485.PNG)

![Image](https://user-images.githubusercontent.com/94624889/197091340-5184fdda-3798-4356-be82-9c271632ee27.PNG)

![Image](https://user-images.githubusercontent.com/94624889/197091339-b9a438a9-0291-4581-bb6e-340006c3d69e.PNG)

![Image](https://user-images.githubusercontent.com/94624889/197091341-e276d112-f219-4634-a995-7f1c3bc608c2.PNG)
