### ISSUE TITLE
Requirements Specifications (M1)

### ISSUE THREAD

**Issue by nobodomon** [junweilam/ICT2101-Team-Project-P4-5#6]
Identify functional user and non-functional requirement.

**Comment by mrdylanchew** [comment]
![Image](https://user-images.githubusercontent.com/94624889/197091641-096c11b0-02dd-4e91-b3f0-b1e5598065e0.PNG)

![Image](https://user-images.githubusercontent.com/94624889/197091639-0686e83b-d759-477d-afdf-1ea94984ef22.PNG)

![Image](https://user-images.githubusercontent.com/94624889/197091640-ba0b0bf2-e304-44d3-b0bf-38ab0a66ab27.PNG)

![Image](https://user-images.githubusercontent.com/94624889/197091638-b88c408a-3bba-4945-974f-12db8c7aa6cc.PNG)
