### ISSUE TITLE
Project estimation (M1)

### ISSUE THREAD

**Issue by mrdylanchew** [junweilam/ICT2101-Team-Project-P4-5#7]

**Comment by 2102673** [comment]
![image](https://user-images.githubusercontent.com/90232284/201245030-3cc904a9-aca8-47c1-89d8-9ca3039434bf.png)
![image](https://user-images.githubusercontent.com/90232284/201245046-6ec6de26-1438-49a3-a6f1-9df438f90539.png)
![image](https://user-images.githubusercontent.com/90232284/201245058-f3d33c0c-f0a6-4ce9-a21b-8b1f2b3a98b5.png)
![image](https://user-images.githubusercontent.com/90232284/201245080-0b8b1454-1ae8-4090-a813-f317b669a2c6.png)
